Repository lit/lit-element, pull requests merged in 2018-12, with the labels that each got.

#329 Add 404 and 500 pages
  docs/404.html
  docs/500.html
  docs/main.py
Labels: Area: docs, cla: yes

#322 [docs] Fix property initialization in properties doc
  docs/try/properties.md
Labels: Area: docs, cla: yes

#327 [docs] Style alert callouts; separate main and theme CSS files; import styles from p-p.org
  docs/_includes/article.html
  docs/_includes/topnav.html
  docs/_layouts/default.html
  docs/css/main.css
  docs/css/theme.css
  docs/images/alerts/info.svg
  docs/images/alerts/warning.svg
  docs/index.md
Labels: Area: docs, cla: yes

#330 [docs] Tutorial fixes
  docs/_data/site.yml
  docs/_includes/projects/try/create/after/my-element.js
  docs/_includes/projects/try/create/before/my-element.js
  docs/_includes/projects/try/events/after/my-element.js
  docs/_includes/projects/try/events/before/my-element.js
  docs/_includes/projects/try/expressions/after/my-element.js
  docs/_includes/projects/try/expressions/before/my-element.js
  docs/_includes/projects/try/properties/after/my-element.js
  docs/_includes/projects/try/properties/before/my-element.js
  docs/_includes/projects/try/style/after/my-element.js
  docs/_includes/projects/try/style/before/my-element.js
  docs/_includes/projects/try/use/after/index.html
  docs/_includes/projects/try/use/after/index.ts
  docs/_includes/projects/try/use/after/my-element.js
  docs/_includes/projects/try/use/before/index.html
  docs/_includes/projects/try/use/before/index.ts
  docs/_includes/projects/try/use/before/my-element.js
  docs/try/create.md
  docs/try/events.md
  docs/try/expressions.md
  docs/try/index.md
  docs/try/properties.md
  docs/try/style.md
  docs/try/use.md
Labels: Area: docs, cla: yes

#331 [docs] Update link to lit-html guide
  README.md
Labels: Area: docs, cla: yes

#332 [docs] shorter headings in try tutorial
  docs/_data/site.yml
  docs/_includes/projects/try/create/after/my-element.js
  docs/_includes/projects/try/create/before/my-element.js
  docs/_includes/projects/try/events/after/my-element.js
  docs/_includes/projects/try/events/before/my-element.js
  docs/_includes/projects/try/expressions/.DS_Store
  docs/_includes/projects/try/import/after/index.html
  docs/_includes/projects/try/import/after/index.ts
  docs/_includes/projects/try/import/after/manifest.json
  docs/_includes/projects/try/import/after/my-element.js
  docs/_includes/projects/try/import/before/index.html
  docs/_includes/projects/try/import/before/index.ts
  docs/_includes/projects/try/import/before/manifest.json
  docs/_includes/projects/try/import/before/my-element.js
  docs/_includes/projects/try/logic/after/index.html
  docs/_includes/projects/try/logic/after/index.ts
  docs/_includes/projects/try/logic/after/manifest.json
  docs/_includes/projects/try/logic/after/my-element.js
  docs/_includes/projects/try/logic/before/index.html
  docs/_includes/projects/try/logic/before/index.ts
  docs/_includes/projects/try/logic/before/manifest.json
  docs/_includes/projects/try/logic/before/my-element.js
  docs/_includes/projects/try/properties/after/my-element.js
  docs/_includes/projects/try/properties/before/my-element.js
  docs/_includes/projects/try/style/after/my-element.js
  docs/_includes/projects/try/style/before/my-element.js
  docs/_includes/projects/try/use/.DS_Store
  docs/try/create.md
  docs/try/events.md
  docs/try/import.md
  docs/try/index.md
  docs/try/logic.md
  docs/try/properties.md
  docs/try/style.md
Labels: cla: yes

#333 Fix broken links from docs tracker rport
  docs/docs/properties.md
  docs/docs/templates/create.md
  docs/tools/setup.md
Labels: cla: yes

#344 [docs] Add scripts for managing docs
  .gitignore
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/LICENSE.md
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/README.md
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-ce.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-ce.js.map
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce-pf.js.map
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd-ce.js.map
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/bundles/webcomponents-sd.js.map
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/custom-elements-es5-adapter-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/webcomponents-bundle-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/webcomponents-ce-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-ce-pf-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/entrypoints/webcomponents-sd-index.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/package.json
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js.map
  docs/build/gh-pages/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js
  docs/build/gh-pages/src/index.html
  docs/build/gh-pages/src/index.js
  docs/build/polymer.json
  docs/package-lock.json
  docs/package.json
Labels: Area: docs, cla: yes

#348 [docs] Restructure toc and pages
  docs/_config.yml
  docs/_data/site.yml
  docs/_guide/index.md
  docs/_guide/lifecycle.md
  docs/_guide/properties.md
  docs/_guide/templates.md
  docs/_guide/tools.md
  docs/_guide/try.md
  docs/_includes/article.html
  docs/_includes/prevnext.html
  docs/_includes/projects/try/create/after/my-element.js
  docs/_includes/projects/try/create/before/my-element.js
  docs/_includes/projects/try/events/after/my-element.js
  docs/_includes/projects/try/events/before/my-element.js
  docs/_includes/projects/try/import/after/index.html
  docs/_includes/projects/try/import/before/index.html
  docs/_includes/projects/try/logic/after/my-element.js
  docs/_includes/projects/try/logic/before/my-element.js
  docs/_includes/projects/try/properties/after/my-element.js
  docs/_includes/projects/try/properties/before/my-element.js
  docs/_includes/projects/try/style/after/my-element.js
  docs/_includes/projects/try/style/before/my-element.js
  docs/_includes/sectiontoc.html
  docs/_includes/topnav.html
  docs/_layouts/default.html
  docs/_layouts/post.html
  docs/docs/index.md
  docs/docs/lifecycle/about.md
  docs/docs/lifecycle/customize.md
  docs/docs/lifecycle/index.md
  docs/docs/lifecycle/methods.md
  docs/docs/templates/compose.md
  docs/docs/templates/create.md
  docs/docs/templates/databinding.md
  docs/docs/templates/design.md
  docs/docs/templates/expressions.md
  docs/docs/templates/index.md
  docs/docs/templates/slots.md
  docs/docs/templates/syntax.md
  docs/index.md
  docs/tools/build.md
  docs/tools/develop.md
  docs/tools/index.md
  docs/tools/quick.md
  docs/tools/sample.md
  docs/try/create.md
  docs/try/events.md
  docs/try/import.md
  docs/try/index.md
  docs/try/logic.md
  docs/try/properties.md
  docs/try/style.md
Labels: cla: yes

#349 Styles
  docs/_data/site.yml
  docs/_guide/styles.md
  docs/_includes/projects/docs/style/before/index.html
  docs/_includes/projects/docs/style/before/index.ts
  docs/_includes/projects/docs/style/before/manifest.json
  docs/_includes/projects/docs/style/before/my-element.js
  docs/_includes/projects/docs/style/bestpracs/index.html
  docs/_includes/projects/docs/style/bestpracs/index.ts
  docs/_includes/projects/docs/style/bestpracs/manifest.json
  docs/_includes/projects/docs/style/bestpracs/my-element.js
  docs/_includes/projects/docs/style/customproperties/index.html
  docs/_includes/projects/docs/style/customproperties/index.ts
  docs/_includes/projects/docs/style/customproperties/manifest.json
  docs/_includes/projects/docs/style/customproperties/my-element.js
  docs/_includes/projects/docs/style/expressions/index.html
  docs/_includes/projects/docs/style/expressions/index.ts
  docs/_includes/projects/docs/style/expressions/manifest.json
  docs/_includes/projects/docs/style/expressions/my-element.js
  docs/_includes/projects/docs/style/host/index.html
  docs/_includes/projects/docs/style/host/index.ts
  docs/_includes/projects/docs/style/host/manifest.json
  docs/_includes/projects/docs/style/host/my-element.js
  docs/_includes/projects/docs/style/hostselector/index.html
  docs/_includes/projects/docs/style/hostselector/index.ts
  docs/_includes/projects/docs/style/hostselector/manifest.json
  docs/_includes/projects/docs/style/hostselector/my-element.js
  docs/_includes/projects/docs/style/inherited/index.html
  docs/_includes/projects/docs/style/inherited/index.ts
  docs/_includes/projects/docs/style/inherited/manifest.json
  docs/_includes/projects/docs/style/inherited/my-element.js
  docs/_includes/projects/docs/style/inherited2/index.html
  docs/_includes/projects/docs/style/inherited2/index.ts
  docs/_includes/projects/docs/style/inherited2/manifest.json
  docs/_includes/projects/docs/style/inherited2/my-element.js
  docs/_includes/projects/docs/style/maindocument/index.html
  docs/_includes/projects/docs/style/maindocument/index.ts
  docs/_includes/projects/docs/style/maindocument/manifest.json
  docs/_includes/projects/docs/style/maindocument/my-element.js
  docs/_includes/projects/docs/style/slotted/index.html
  docs/_includes/projects/docs/style/slotted/index.ts
  docs/_includes/projects/docs/style/slotted/manifest.json
  docs/_includes/projects/docs/style/slotted/my-element.js
  docs/_includes/projects/docs/style/smalltheme/index.html
  docs/_includes/projects/docs/style/smalltheme/index.ts
  docs/_includes/projects/docs/style/smalltheme/manifest.json
  docs/_includes/projects/docs/style/smalltheme/my-element.js
  docs/_includes/projects/docs/style/smalltheme/my-styles.js
Labels: cla: yes

#350 [docs] Generate API docs
  docs/_config.yml
  docs/_includes/topnav.html
  docs/api/assets/css/main.css
  docs/api/assets/css/main.css.map
  docs/api/assets/images/icons.png
  docs/api/assets/images/icons@2x.png
  docs/api/assets/images/widgets.png
  docs/api/assets/images/widgets@2x.png
  docs/api/assets/js/main.js
  docs/api/assets/js/search.js
  docs/api/classes/_lib_updating_element_.updatingelement.html
  docs/api/classes/_lit_element_.litelement.html
  docs/api/index.html
  docs/api/interfaces/_lib_updating_element_.attributeserializer.html
  docs/api/interfaces/_lib_updating_element_.haschanged.html
  docs/api/interfaces/_lib_updating_element_.propertydeclaration.html
  docs/api/interfaces/_lib_updating_element_.propertydeclarations.html
  docs/api/modules/_lib_decorators_.html
  docs/api/modules/_lib_updating_element_.html
  docs/api/modules/_lit_element_.html
  docs/app.yaml
Labels: Area: docs, cla: yes

#292 Update decorator types
  CHANGELOG.md
  src/lib/decorators.ts
Labels: Priority: Medium, cla: yes

#367 Use lit-html 1.0 rc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cla: yes

#307 Fully support Closure compiler including ADVANCED_OPTIMIZATIONS
  src/lib/updating-element.ts
  src/lit-element.ts
Labels: cla: yes, source:hooli

#357 Adds passive/once to `EventListenerOptions` type
  CHANGELOG.md
  package-lock.json
  src/lib/decorators.ts
  src/test/lib/decorators_test.ts
Labels: cla: yes

#360 Redesign
  docs/_config.yml
  docs/_guide/index.md
  docs/_guide/lifecycle.md
  docs/_layouts/default.html
  docs/css/main.css
  docs/css/theme.css
  docs/images/logos/logo_email.svg
  docs/images/logos/logo_github.svg
  docs/images/logos/logo_slack.svg
  docs/images/logos/logo_twitter.svg
  docs/index.md
  docs/src/stack-blitz.js
Labels: Area: docs, cla: yes

#359 Ensure user accessor is never overridden
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/updating-element.ts
  src/test/lit-element_test.ts
Labels: cla: yes

#369 Changes property options to support `converter`
  CHANGELOG.md
  README.md
  demo/lit-element.html
  src/demo/ts-element.ts
  src/lib/updating-element.ts
  src/test/lit-element_test.ts
Labels: cla: yes

#368 Adds `performUpdate` and defers `update` until connection
  CHANGELOG.md
  README.md
  src/lib/updating-element.ts
  src/test/lib/decorators_test.ts
  src/test/lib/updating-element_test.ts
  src/test/lit-element_test.ts
  test/runner.html
Labels: cla: yes

#378 Update links in generated API docs
  docs/api/classes/_lib_updating_element_.updatingelement.html
  docs/api/classes/_lit_element_.litelement.html
  docs/api/interfaces/_lib_updating_element_.attributeserializer.html
  docs/api/interfaces/_lib_updating_element_.haschanged.html
  docs/api/interfaces/_lib_updating_element_.propertydeclaration.html
  docs/api/modules/_lib_decorators_.html
  docs/api/modules/_lib_updating_element_.html
Labels: cla: yes

#387 Update try for feedback
  docs/_guide/try.md
  docs/_includes/projects/try/events/after/my-element.js
  docs/_includes/projects/try/events/before/my-element.js
  docs/_includes/projects/try/logic/after/my-element.js
  docs/_includes/projects/try/logic/before/my-element.js
  docs/_includes/projects/try/style/after/my-element.js
  docs/_includes/projects/try/style/before/my-element.js
Labels: cla: yes

#380 Properties docs
  docs/_guide/properties.md
  docs/_guide/stuff
  docs/_includes/project.html
  docs/_includes/projects/docs/properties/attribute/my-element.js
  docs/_includes/projects/docs/properties/type/my-element.js
  docs/_includes/projects/properties/accessorssubclassing/index.html
  docs/_includes/projects/properties/accessorssubclassing/index.ts
  docs/_includes/projects/properties/accessorssubclassing/manifest.json
  docs/_includes/projects/properties/accessorssubclassing/my-element.js
  docs/_includes/projects/properties/accessorssubclassing/super-element.js
  docs/_includes/projects/properties/attributeconverter/index.html
  docs/_includes/projects/properties/attributeconverter/index.ts
  docs/_includes/projects/properties/attributeconverter/manifest.json
  docs/_includes/projects/properties/attributeconverter/my-element.js
  docs/_includes/projects/properties/attributeobserve/index.html
  docs/_includes/projects/properties/attributeobserve/index.ts
  docs/_includes/projects/properties/attributeobserve/manifest.json
  docs/_includes/projects/properties/attributeobserve/my-element.js
  docs/_includes/projects/properties/attributereflect/index.html
  docs/_includes/projects/properties/attributereflect/index.ts
  docs/_includes/projects/properties/attributereflect/manifest.json
  docs/_includes/projects/properties/attributereflect/my-element.js
  docs/_includes/projects/properties/customsetter/index.html
  docs/_includes/projects/properties/customsetter/index.ts
  docs/_includes/projects/properties/customsetter/manifest.json
  docs/_includes/projects/properties/customsetter/my-element.js
  docs/_includes/projects/properties/declare/index.html
  docs/_includes/projects/properties/declare/index.ts
  docs/_includes/projects/properties/declare/manifest.json
  docs/_includes/projects/properties/declare/my-element.js
  docs/_includes/projects/properties/declaretypescript/index.html
  docs/_includes/projects/properties/declaretypescript/index.ts
  docs/_includes/projects/properties/declaretypescript/manifest.json
  docs/_includes/projects/properties/declaretypescript/my-element.ts
  docs/_includes/projects/properties/defaultconverter/index.html
  docs/_includes/projects/properties/defaultconverter/index.ts
  docs/_includes/projects/properties/defaultconverter/manifest.json
  docs/_includes/projects/properties/defaultconverter/my-element.js
  docs/_includes/projects/properties/haschanged/index.html
  docs/_includes/projects/properties/haschanged/index.ts
  docs/_includes/projects/properties/haschanged/manifest.json
  docs/_includes/projects/properties/haschanged/my-element.js
  docs/_includes/projects/properties/init/index.html
  docs/_includes/projects/properties/init/index.ts
  docs/_includes/projects/properties/init/manifest.json
  docs/_includes/projects/properties/init/my-element.js
  docs/_includes/projects/properties/initmarkup/index.html
  docs/_includes/projects/properties/initmarkup/index.ts
  docs/_includes/projects/properties/initmarkup/manifest.json
  docs/_includes/projects/properties/initmarkup/my-element.js
  docs/_includes/projects/properties/inittypescript/index.html
  docs/_includes/projects/properties/inittypescript/index.ts
  docs/_includes/projects/properties/inittypescript/manifest.json
  docs/_includes/projects/properties/inittypescript/my-element.ts
Labels: cla: yes

#394 Updated latest main.css
  docs/css/main.css
Labels: cla: yes

#393 restructure toc
  docs/_config.yml
  docs/_data/guide.yml
  docs/_data/try.yml
  docs/_guide/deploy.md
  docs/_guide/index.md
  docs/_guide/lifecycle.md
  docs/_guide/properties.md
  docs/_guide/start.md
  docs/_guide/stuff
  docs/_guide/styles.md
  docs/_guide/templates.md
  docs/_guide/tools.md
  docs/_guide/try.md
  docs/_includes/projects/try/create/after/my-element.js
  docs/_includes/projects/try/create/before/my-element.js
  docs/_includes/projects/try/events/after/my-element.js
  docs/_includes/projects/try/events/before/my-element.js
  docs/_includes/projects/try/import/after/index.html
  docs/_includes/projects/try/import/before/index.html
  docs/_includes/projects/try/logic/after/my-element.js
  docs/_includes/projects/try/logic/before/my-element.js
  docs/_includes/projects/try/properties/after/my-element.js
  docs/_includes/projects/try/properties/before/my-element.js
  docs/_includes/projects/try/style/after/my-element.js
  docs/_includes/projects/try/style/before/my-element.js
  docs/_includes/topnav.html
  docs/_layouts/guide.html
  docs/_layouts/try.html
  docs/_try/create.md
  docs/_try/events.md
  docs/_try/import.md
  docs/_try/index.md
  docs/_try/logic.md
  docs/_try/properties.md
  docs/_try/style.md
  docs/index.md
Labels: cla: yes

#279 Enable TypeScript declaration maps
  .gitignore
  tsconfig.json
Labels: cla: yes

#405 typo in start.md
  docs/_guide/start.md
Labels: cla: yes
