Repository lit/lit-element, pull requests merged in 2019-03, with the labels that each got.

#597 Update package description in package.json
  package.json
Labels: cla: yes

#599 Remove unnecessary type assertions
  src/lib/decorators.ts
  src/lib/updating-element.ts
  src/lit-element.ts
  src/test/lib/decorators_test.ts
  src/test/lit-element_styling_test.ts
  tslint.json
Labels: cla: yes

#610 Ensure attribute reflected from property is correct
  CHANGELOG.md
  src/lib/updating-element.ts
  src/test/lib/updating-element_test.ts
Labels: cla: yes

#606 Schedules `requestUpdate` in `initialize` rather than `connectedCallback`
  CHANGELOG.md
  src/lib/updating-element.ts
  src/test/lib/updating-element_test.ts
Labels: cla: yes

#607 Handle exceptions during update so that they do not break subsequent updates
  CHANGELOG.md
  src/lib/updating-element.ts
  src/test/lib/updating-element_test.ts
  src/test/lit-element_test.ts
Labels: cla: yes

#602 Update Lifecycle doc's broken link to Properties
  docs/_guide/lifecycle.md
Labels: cla: yes

#598 Add homepage URL to package.json
  package.json
Labels: cla: yes

#627 Add `np` for releases
  package-lock.json
  package.json
Labels: cla: yes

#631 Docs publish decorators plugin fix
  docs/_guide/publish.md
Labels: cla: yes

#624 Fix broken anchors and links to them
  docs/_guide/styles.md
Labels: cla: yes

#622 Remove obsolete link
  docs/_try/create.md
Labels: cla: yes

#615 docs: fix included code snippets for named slots in templates
  docs/_guide/templates.md
Labels: cla: yes

#518 [docs] Add information about lit-html features in template syntax
  docs/_guide/templates.md
Labels: Area: docs, Status: In Progress, cla: yes

#576 Added section about custom element lifecycles.
  docs/_guide/lifecycle.md
Labels: Area: docs, cla: yes

#623 Adapt Arthur's lit-html README for lit-element
  docs/README.md
Labels: cla: yes

#636 [docs] Remove z-index on alert style
  docs/css/main.css
Labels: Area: docs, cla: yes

#638 Update to latest typescript
  package-lock.json
  package.json
Labels: cla: yes
