Repository lit/lit-element, pull requests merged in 2019-02, with the labels that each got.

#524 `unsafeCss` -> `unsafeCSS` for consistency with lit-html's `unsafeHTML`
  CHANGELOG.md
  docs/api/assets/js/search.js
  docs/api/modules/_lib_css_tag_.html
  src/lib/css-tag.ts
  src/test/lit-element_styling_test.ts
Labels: cla: yes

#515 Simplify Readme
  CONTRIBUTING.md
  README.md
Labels: cla: yes

#527 Fix for incorrect implementation of `adoptedStylesheets`
  CHANGELOG.md
  src/lib/css-tag.ts
Labels: cla: yes

#517 [docs] Fix missing anchor
  docs/_guide/properties.md
Labels: cla: yes

#508 Adds `toString` to CSSResult
  src/lib/css-tag.ts
  src/test/lit-element_styling_test.ts
Labels: cla: yes

#489 [docs] Code samples for accessors with subclassing && tidy up doc
  docs/_guide/properties.md
  docs/_includes/projects/properties/accessorssubclassing/index.html
  docs/_includes/projects/properties/accessorssubclassing/index.ts
  docs/_includes/projects/properties/accessorssubclassing/manifest.json
  docs/_includes/projects/properties/accessorssubclassing/my-element.js
  docs/_includes/projects/properties/accessorssubclassing/sub-element.js
  docs/_includes/projects/properties/accessorssubclassing/super-element.js
  docs/_includes/projects/properties/customsetter/my-element.js
Labels: cla: yes

#503 [docs] Edits on new Styles docs
  docs/_guide/styles.md
  docs/_guide/templates.md
  docs/_includes/projects/docs/style/before/my-element.js
  docs/_includes/projects/docs/style/expressions/index.html
  docs/_includes/projects/docs/style/expressions/my-element.js
  docs/_includes/projects/docs/style/host/my-element.js
  docs/_includes/projects/docs/style/hostselector/index.html
  docs/_includes/projects/docs/style/inherited/index.html
  docs/_includes/projects/docs/style/inherited2/index.ts
  docs/_includes/projects/docs/style/inherited2/manifest.json
  docs/_includes/projects/docs/style/maindocument/index.html
  docs/_includes/projects/docs/style/maindocument/index.ts
  docs/_includes/projects/docs/style/maindocument/manifest.json
  docs/_includes/projects/docs/style/maindocument/my-element.js
  docs/_includes/projects/docs/style/slotted/index.ts
  docs/_includes/projects/docs/style/slotted/manifest.json
  docs/_includes/projects/docs/style/smalltheme/index.html
  docs/_includes/projects/docs/style/smalltheme/index.ts
  docs/_includes/projects/docs/style/smalltheme/manifest.json
  docs/_includes/projects/docs/style/smalltheme/my-element.js
  docs/_includes/projects/docs/style/smalltheme/my-styles.js
  docs/_includes/projects/style/bestpracs/index.html
  docs/_includes/projects/style/bestpracs/index.ts
  docs/_includes/projects/style/bestpracs/manifest.json
  docs/_includes/projects/style/bestpracs/my-element.js
  docs/_includes/projects/style/customproperties/index.html
  docs/_includes/projects/style/customproperties/index.ts
  docs/_includes/projects/style/customproperties/manifest.json
  docs/_includes/projects/style/customproperties/my-element.js
  docs/_includes/projects/style/hostselector/index.html
  docs/_includes/projects/style/hostselector/index.ts
  docs/_includes/projects/style/hostselector/manifest.json
  docs/_includes/projects/style/hostselector/my-element.js
  docs/_includes/projects/style/inherited/index.html
  docs/_includes/projects/style/inherited/index.ts
  docs/_includes/projects/style/inherited/manifest.json
  docs/_includes/projects/style/inherited/my-element.js
  docs/_includes/projects/style/inherited2/index.html
  docs/_includes/projects/style/inherited2/index.ts
  docs/_includes/projects/style/inherited2/manifest.json
  docs/_includes/projects/style/inherited2/my-element.js
  docs/_includes/projects/style/slotted/index.html
  docs/_includes/projects/style/slotted/index.ts
  docs/_includes/projects/style/slotted/manifest.json
  docs/_includes/projects/style/slotted/my-element.js
  docs/_includes/projects/style/theming/index.html
  docs/_includes/projects/style/theming/index.ts
  docs/_includes/projects/style/theming/manifest.json
  docs/_includes/projects/style/theming/my-element.js
  docs/package.json
Labels: cla: no

#460 [docs] Update docs to reflect #454 change to remove accessor wrapping
  docs/_guide/properties.md
  docs/_includes/projects/properties/accessorssubclassing/index.html
  docs/_includes/projects/properties/accessorssubclassing/index.ts
  docs/_includes/projects/properties/accessorssubclassing/manifest.json
  docs/_includes/projects/properties/accessorssubclassing/my-element.js
  docs/_includes/projects/properties/accessorssubclassing/sub-element.js
  docs/_includes/projects/properties/accessorssubclassing/super-element.js
  docs/_includes/projects/properties/customsetter/my-element.js
Labels: Area: docs, cla: yes

#413 [docs] Draft events docs ready for review
  docs/_data/guide.yml
  docs/_guide/events.md
  docs/_includes/projects/events/child/index.html
  docs/_includes/projects/events/child/index.ts
  docs/_includes/projects/events/child/manifest.json
  docs/_includes/projects/events/child/my-element.js
  docs/_includes/projects/events/childimperative/index.html
  docs/_includes/projects/events/childimperative/index.ts
  docs/_includes/projects/events/childimperative/manifest.json
  docs/_includes/projects/events/childimperative/my-element.js
  docs/_includes/projects/events/events/index.html
  docs/_includes/projects/events/events/index.ts
  docs/_includes/projects/events/events/manifest.json
  docs/_includes/projects/events/events/my-element.js
  docs/_includes/projects/events/host/index.html
  docs/_includes/projects/events/host/index.ts
  docs/_includes/projects/events/host/manifest.json
  docs/_includes/projects/events/host/my-element.js
Labels: Area: docs, cla: yes

#536 Add version global
  .clang-format
  src/demo/ts-element.ts
  src/env.d.ts
  src/lib/css-tag.ts
  src/lib/decorators.ts
  src/lib/updating-element.ts
  src/lit-element.ts
  src/test/lib/decorators_test.ts
  src/test/lib/updating-element_test.ts
  src/test/lit-element_styling_test.ts
  src/test/lit-element_test.ts
  src/test/test-helpers.ts
Labels: cla: yes

#457 Remove almost all uses of `any`.
  src/lib/decorators.ts
  src/lib/updating-element.ts
  src/lit-element.ts
  src/test/lib/decorators_test.ts
  src/test/lib/updating-element_test.ts
  src/test/lit-element_styling_test.ts
  src/test/lit-element_test.ts
  tsconfig.json
  tslint.json
Labels: cla: yes

#535 [docs] Start: Add missing step
  docs/_guide/start.md
Labels: cla: yes

#539 broken templates link
  docs/_guide/lifecycle.md
Labels: cla: yes

#540 broken properties link
  docs/_guide/lifecycle.md
Labels: cla: yes

#541 [skip ci] Prepare for 2.0 release
  CHANGELOG.md
Labels: cla: yes

#521 [docs] Simplify home page
  docs/_includes/project.html
  docs/_includes/projects/index-typescript/custom-greeting.ts
  docs/css/main.css
  docs/index.md
  docs/src/stack-blitz.js
Labels: cla: yes

#543 Use lit-html 1.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/lit-element.ts
Labels: cla: yes

#544 [docs] Last-minute tweaks to home page
  docs/_includes/projects/index-typescript/index.html
  docs/_includes/projects/index-typescript/index.ts
  docs/_includes/projects/index-typescript/manifest.json
  docs/_includes/projects/index-typescript/simple-greeting.ts
  docs/_includes/projects/index/index.html
  docs/_includes/projects/index/index.ts
  docs/_includes/projects/index/manifest.json
  docs/_includes/projects/index/simple-greeting.js
  docs/index.md
  docs/src/stack-blitz.js
Labels: cla: yes

#557 [docs] Spelling Mistake: changed "tern" to "term"
  docs/_guide/styles.md
Labels: cla: yes

#558 Remove semicolon from customElement decorator on README example
  README.md
Labels: cla: yes

#566 Add @ExportDecoratedItems annotations to query and queryAll decorators.
  CHANGELOG.md
  src/lib/decorators.ts
  src/lit-element.ts
Labels: cla: yes

#567 [docs] Fix minor typo in updateComplete section
  docs/_guide/lifecycle.md
Labels: cla: yes

#554 Update use of Object.assign on Arrays
  docs/_includes/projects/properties/defaultconverter/my-element.js
Labels: Area: docs, cla: yes

#568 Fix typo.
  docs/_guide/styles.md
Labels: Area: docs, cla: yes

#556 [docs] Fix my-element.js for the completed code
  docs/_try/create.md
Labels: Area: docs, cla: yes

#569 Sync stylesheet; Place anchors below header
  docs/css/main.css
  docs/css/theme.css
Labels: Area: docs, cla: yes

#571 Fix syntax
  docs/_guide/styles.md
Labels: Area: docs, cla: no

#585 change syntax for static styles so that polymer-cli supports it
  docs/_guide/styles.md
Labels: cla: yes

#583 remove in development status from api-readme
  docs/_api/api-readme.md
Labels: cla: yes

#573 Remove `static` from composable getters,
  docs/_guide/templates.md
  docs/_includes/projects/docs/templates/compose/my-page.js
Labels: cla: yes

#552 Remove "Quick Start" section from Introduction
  docs/_guide/index.md
Labels: Area: docs, cla: yes

#546 Fix cssResult.toString type
  src/lib/css-tag.ts
Labels: cla: yes

#595 Add file extensions fo imports where missing.
  src/lit-element.ts
Labels: cla: yes

#593 Add section indicator in top nav
  docs/_api/theme/layouts/default.hbs
  docs/_includes/topnav.html
  docs/api/assets/js/search.js
  docs/api/classes/_lib_css_tag_.cssresult.html
  docs/api/classes/_lib_updating_element_.updatingelement.html
  docs/api/classes/_lit_element_.litelement.html
  docs/api/globals.html
  docs/api/index.html
  docs/api/interfaces/_lib_updating_element_.complexattributeconverter.html
  docs/api/interfaces/_lib_updating_element_.haschanged.html
  docs/api/interfaces/_lib_updating_element_.propertydeclaration.html
  docs/api/interfaces/_lib_updating_element_.propertydeclarations.html
  docs/api/interfaces/_lit_element_.cssresultarray.html
  docs/api/modules/_demo_ts_element_.html
  docs/api/modules/_lib_css_tag_.html
  docs/api/modules/_lib_decorators_.html
  docs/api/modules/_lib_updating_element_.html
  docs/api/modules/_lit_element_.html
  docs/api/modules/_test_lit_element_styling_test_.html
  docs/api/modules/_test_lit_element_test_.html
  docs/api/modules/_test_test_helpers_.html
  docs/css/main.css
  docs/css/theme.css
Labels: Area: docs, cla: yes
